/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables;


import db_jooq.DefaultSchema;
import db_jooq.Keys;
import db_jooq.tables.records.AmministratoreRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Amministratore extends TableImpl<AmministratoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>AMMINISTRATORE</code>
     */
    public static final Amministratore AMMINISTRATORE = new Amministratore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmministratoreRecord> getRecordType() {
        return AmministratoreRecord.class;
    }

    /**
     * The column <code>AMMINISTRATORE.CF</code>.
     */
    public final TableField<AmministratoreRecord, String> CF = createField(DSL.name("CF"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>AMMINISTRATORE.Nome</code>.
     */
    public final TableField<AmministratoreRecord, String> NOME = createField(DSL.name("Nome"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>AMMINISTRATORE.Cognome</code>.
     */
    public final TableField<AmministratoreRecord, String> COGNOME = createField(DSL.name("Cognome"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>AMMINISTRATORE.Email</code>.
     */
    public final TableField<AmministratoreRecord, String> EMAIL = createField(DSL.name("Email"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private Amministratore(Name alias, Table<AmministratoreRecord> aliased) {
        this(alias, aliased, null);
    }

    private Amministratore(Name alias, Table<AmministratoreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>AMMINISTRATORE</code> table reference
     */
    public Amministratore(String alias) {
        this(DSL.name(alias), AMMINISTRATORE);
    }

    /**
     * Create an aliased <code>AMMINISTRATORE</code> table reference
     */
    public Amministratore(Name alias) {
        this(alias, AMMINISTRATORE);
    }

    /**
     * Create a <code>AMMINISTRATORE</code> table reference
     */
    public Amministratore() {
        this(DSL.name("AMMINISTRATORE"), null);
    }

    public <O extends Record> Amministratore(Table<O> child, ForeignKey<O, AmministratoreRecord> key) {
        super(child, key, AMMINISTRATORE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AmministratoreRecord> getPrimaryKey() {
        return Keys.AMMINISTRATORE__PK_AMMINISTRATORE;
    }

    @Override
    public Amministratore as(String alias) {
        return new Amministratore(DSL.name(alias), this);
    }

    @Override
    public Amministratore as(Name alias) {
        return new Amministratore(alias, this);
    }

    @Override
    public Amministratore as(Table<?> alias) {
        return new Amministratore(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Amministratore rename(String name) {
        return new Amministratore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Amministratore rename(Name name) {
        return new Amministratore(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Amministratore rename(Table<?> name) {
        return new Amministratore(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
