/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables;


import db_jooq.DefaultSchema;
import db_jooq.Keys;
import db_jooq.tables.records.CampogaraRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Campogara extends TableImpl<CampogaraRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CAMPOGARA</code>
     */
    public static final Campogara CAMPOGARA = new Campogara();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampogaraRecord> getRecordType() {
        return CampogaraRecord.class;
    }

    /**
     * The column <code>CAMPOGARA.ID</code>.
     */
    public final TableField<CampogaraRecord, String> ID = createField(DSL.name("ID"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>CAMPOGARA.Paese</code>.
     */
    public final TableField<CampogaraRecord, String> PAESE = createField(DSL.name("Paese"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>CAMPOGARA.CorpoIdrico</code>.
     */
    public final TableField<CampogaraRecord, String> CORPOIDRICO = createField(DSL.name("CorpoIdrico"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CAMPOGARA.Lunghezza</code>.
     */
    public final TableField<CampogaraRecord, Integer> LUNGHEZZA = createField(DSL.name("Lunghezza"), SQLDataType.INTEGER, this, "");

    private Campogara(Name alias, Table<CampogaraRecord> aliased) {
        this(alias, aliased, null);
    }

    private Campogara(Name alias, Table<CampogaraRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CAMPOGARA</code> table reference
     */
    public Campogara(String alias) {
        this(DSL.name(alias), CAMPOGARA);
    }

    /**
     * Create an aliased <code>CAMPOGARA</code> table reference
     */
    public Campogara(Name alias) {
        this(alias, CAMPOGARA);
    }

    /**
     * Create a <code>CAMPOGARA</code> table reference
     */
    public Campogara() {
        this(DSL.name("CAMPOGARA"), null);
    }

    public <O extends Record> Campogara(Table<O> child, ForeignKey<O, CampogaraRecord> key) {
        super(child, key, CAMPOGARA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CampogaraRecord> getPrimaryKey() {
        return Keys.CAMPOGARA__PK_CAMPOGARA;
    }

    @Override
    public Campogara as(String alias) {
        return new Campogara(DSL.name(alias), this);
    }

    @Override
    public Campogara as(Name alias) {
        return new Campogara(alias, this);
    }

    @Override
    public Campogara as(Table<?> alias) {
        return new Campogara(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Campogara rename(String name) {
        return new Campogara(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Campogara rename(Name name) {
        return new Campogara(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Campogara rename(Table<?> name) {
        return new Campogara(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
