/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables;


import db_jooq.DefaultSchema;
import db_jooq.Keys;
import db_jooq.tables.records.GaraRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function16;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row16;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gara extends TableImpl<GaraRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GARA</code>
     */
    public static final Gara GARA = new Gara();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GaraRecord> getRecordType() {
        return GaraRecord.class;
    }

    /**
     * The column <code>GARA.Codice</code>.
     */
    public final TableField<GaraRecord, String> CODICE = createField(DSL.name("Codice"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>GARA.NumProva</code>.
     */
    public final TableField<GaraRecord, Integer> NUMPROVA = createField(DSL.name("NumProva"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GARA.Tecnica</code>.
     */
    public final TableField<GaraRecord, String> TECNICA = createField(DSL.name("Tecnica"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>GARA.CriterioPunti</code>.
     */
    public final TableField<GaraRecord, String> CRITERIOPUNTI = createField(DSL.name("CriterioPunti"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>GARA.MinPersone</code>.
     */
    public final TableField<GaraRecord, Integer> MINPERSONE = createField(DSL.name("MinPersone"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GARA.MaxPersone</code>.
     */
    public final TableField<GaraRecord, Integer> MAXPERSONE = createField(DSL.name("MaxPersone"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GARA.StatoGara</code>.
     */
    public final TableField<GaraRecord, String> STATOGARA = createField(DSL.name("StatoGara"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("'NON_INIZIATA'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GARA.StatoConferma</code>.
     */
    public final TableField<GaraRecord, String> STATOCONFERMA = createField(DSL.name("StatoConferma"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("'IN_ATTESA'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GARA.TipoGara</code>.
     */
    public final TableField<GaraRecord, String> TIPOGARA = createField(DSL.name("TipoGara"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>GARA.Data</code>.
     */
    public final TableField<GaraRecord, LocalDate> DATA = createField(DSL.name("Data"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>GARA.Campionato</code>.
     */
    public final TableField<GaraRecord, String> CAMPIONATO = createField(DSL.name("Campionato"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>GARA.Arbitro</code>.
     */
    public final TableField<GaraRecord, String> ARBITRO = createField(DSL.name("Arbitro"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>GARA.AmministratoreProposta</code>.
     */
    public final TableField<GaraRecord, String> AMMINISTRATOREPROPOSTA = createField(DSL.name("AmministratoreProposta"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>GARA.AmministratoreAccettazione</code>.
     */
    public final TableField<GaraRecord, String> AMMINISTRATOREACCETTAZIONE = createField(DSL.name("AmministratoreAccettazione"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>GARA.Societa</code>.
     */
    public final TableField<GaraRecord, String> SOCIETA = createField(DSL.name("Societa"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>GARA.CampoGara</code>.
     */
    public final TableField<GaraRecord, String> CAMPOGARA = createField(DSL.name("CampoGara"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Gara(Name alias, Table<GaraRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gara(Name alias, Table<GaraRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>GARA</code> table reference
     */
    public Gara(String alias) {
        this(DSL.name(alias), GARA);
    }

    /**
     * Create an aliased <code>GARA</code> table reference
     */
    public Gara(Name alias) {
        this(alias, GARA);
    }

    /**
     * Create a <code>GARA</code> table reference
     */
    public Gara() {
        this(DSL.name("GARA"), null);
    }

    public <O extends Record> Gara(Table<O> child, ForeignKey<O, GaraRecord> key) {
        super(child, key, GARA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<GaraRecord> getPrimaryKey() {
        return Keys.GARA__PK_GARA;
    }

    @Override
    public List<ForeignKey<GaraRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GARA__FK_GARA_PK_CAMPIONATO, Keys.GARA__FK_GARA_PK_ARBITRO, Keys.GARA__FK_GARA_PK_AMMINISTRATORE, Keys.GARA__FK_GARA_PK_SOCIETA, Keys.GARA__FK_GARA_PK_CAMPOGARA);
    }

    private transient Campionato _campionato;
    private transient Arbitro _arbitro;
    private transient Amministratore _amministratore;
    private transient Societa _societa;
    private transient Campogara _campogara;

    /**
     * Get the implicit join path to the <code>CAMPIONATO</code> table.
     */
    public Campionato campionato() {
        if (_campionato == null)
            _campionato = new Campionato(this, Keys.GARA__FK_GARA_PK_CAMPIONATO);

        return _campionato;
    }

    /**
     * Get the implicit join path to the <code>ARBITRO</code> table.
     */
    public Arbitro arbitro() {
        if (_arbitro == null)
            _arbitro = new Arbitro(this, Keys.GARA__FK_GARA_PK_ARBITRO);

        return _arbitro;
    }

    /**
     * Get the implicit join path to the <code>AMMINISTRATORE</code> table.
     */
    public Amministratore amministratore() {
        if (_amministratore == null)
            _amministratore = new Amministratore(this, Keys.GARA__FK_GARA_PK_AMMINISTRATORE);

        return _amministratore;
    }

    /**
     * Get the implicit join path to the <code>SOCIETA</code> table.
     */
    public Societa societa() {
        if (_societa == null)
            _societa = new Societa(this, Keys.GARA__FK_GARA_PK_SOCIETA);

        return _societa;
    }

    /**
     * Get the implicit join path to the <code>CAMPOGARA</code> table.
     */
    public Campogara campogara() {
        if (_campogara == null)
            _campogara = new Campogara(this, Keys.GARA__FK_GARA_PK_CAMPOGARA);

        return _campogara;
    }

    @Override
    public Gara as(String alias) {
        return new Gara(DSL.name(alias), this);
    }

    @Override
    public Gara as(Name alias) {
        return new Gara(alias, this);
    }

    @Override
    public Gara as(Table<?> alias) {
        return new Gara(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gara rename(String name) {
        return new Gara(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gara rename(Name name) {
        return new Gara(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gara rename(Table<?> name) {
        return new Gara(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row16 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, Integer, String, String, Integer, Integer, String, String, String, LocalDate, String, String, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function16<? super String, ? super Integer, ? super String, ? super String, ? super Integer, ? super Integer, ? super String, ? super String, ? super String, ? super LocalDate, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function16<? super String, ? super Integer, ? super String, ? super String, ? super Integer, ? super Integer, ? super String, ? super String, ? super String, ? super LocalDate, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
