/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables;


import db_jooq.DefaultSchema;
import db_jooq.Keys;
import db_jooq.tables.records.PartecipaRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Partecipa extends TableImpl<PartecipaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PARTECIPA</code>
     */
    public static final Partecipa PARTECIPA = new Partecipa();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartecipaRecord> getRecordType() {
        return PartecipaRecord.class;
    }

    /**
     * The column <code>PARTECIPA.IdPunteggio</code>.
     */
    public final TableField<PartecipaRecord, String> IDPUNTEGGIO = createField(DSL.name("IdPunteggio"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PARTECIPA.IdTurno</code>.
     */
    public final TableField<PartecipaRecord, String> IDTURNO = createField(DSL.name("IdTurno"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PARTECIPA.Concorrente</code>.
     */
    public final TableField<PartecipaRecord, String> CONCORRENTE = createField(DSL.name("Concorrente"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>PARTECIPA.NumPunti</code>.
     */
    public final TableField<PartecipaRecord, Integer> NUMPUNTI = createField(DSL.name("NumPunti"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PARTECIPA.Squalifica</code>.
     */
    public final TableField<PartecipaRecord, Boolean> SQUALIFICA = createField(DSL.name("Squalifica"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    private Partecipa(Name alias, Table<PartecipaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Partecipa(Name alias, Table<PartecipaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PARTECIPA</code> table reference
     */
    public Partecipa(String alias) {
        this(DSL.name(alias), PARTECIPA);
    }

    /**
     * Create an aliased <code>PARTECIPA</code> table reference
     */
    public Partecipa(Name alias) {
        this(alias, PARTECIPA);
    }

    /**
     * Create a <code>PARTECIPA</code> table reference
     */
    public Partecipa() {
        this(DSL.name("PARTECIPA"), null);
    }

    public <O extends Record> Partecipa(Table<O> child, ForeignKey<O, PartecipaRecord> key) {
        super(child, key, PARTECIPA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<PartecipaRecord> getPrimaryKey() {
        return Keys.PARTECIPA__PK_PARTECIPA;
    }

    @Override
    public List<ForeignKey<PartecipaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PARTECIPA__FK_PARTECIPA_PK_TURNO, Keys.PARTECIPA__FK_PARTECIPA_PK_CONCORRENTE);
    }

    private transient Turno _turno;
    private transient Concorrente _concorrente;

    /**
     * Get the implicit join path to the <code>TURNO</code> table.
     */
    public Turno turno() {
        if (_turno == null)
            _turno = new Turno(this, Keys.PARTECIPA__FK_PARTECIPA_PK_TURNO);

        return _turno;
    }

    /**
     * Get the implicit join path to the <code>CONCORRENTE</code> table.
     */
    public Concorrente concorrente() {
        if (_concorrente == null)
            _concorrente = new Concorrente(this, Keys.PARTECIPA__FK_PARTECIPA_PK_CONCORRENTE);

        return _concorrente;
    }

    @Override
    public Partecipa as(String alias) {
        return new Partecipa(DSL.name(alias), this);
    }

    @Override
    public Partecipa as(Name alias) {
        return new Partecipa(alias, this);
    }

    @Override
    public Partecipa as(Table<?> alias) {
        return new Partecipa(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Partecipa rename(String name) {
        return new Partecipa(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Partecipa rename(Name name) {
        return new Partecipa(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Partecipa rename(Table<?> name) {
        return new Partecipa(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, Integer, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super String, ? super String, ? super String, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super String, ? super String, ? super String, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
