/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables;


import db_jooq.DefaultSchema;
import db_jooq.Keys;
import db_jooq.tables.records.RecensisceRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recensisce extends TableImpl<RecensisceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>RECENSISCE</code>
     */
    public static final Recensisce RECENSISCE = new Recensisce();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecensisceRecord> getRecordType() {
        return RecensisceRecord.class;
    }

    /**
     * The column <code>RECENSISCE.IdRecensione</code>.
     */
    public final TableField<RecensisceRecord, String> IDRECENSIONE = createField(DSL.name("IdRecensione"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>RECENSISCE.CodiceGara</code>.
     */
    public final TableField<RecensisceRecord, String> CODICEGARA = createField(DSL.name("CodiceGara"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>RECENSISCE.Concorrente</code>.
     */
    public final TableField<RecensisceRecord, String> CONCORRENTE = createField(DSL.name("Concorrente"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>RECENSISCE.Titolo</code>.
     */
    public final TableField<RecensisceRecord, String> TITOLO = createField(DSL.name("Titolo"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>RECENSISCE.Voto</code>.
     */
    public final TableField<RecensisceRecord, Integer> VOTO = createField(DSL.name("Voto"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>RECENSISCE.Commento</code>.
     */
    public final TableField<RecensisceRecord, String> COMMENTO = createField(DSL.name("Commento"), SQLDataType.CLOB, this, "");

    private Recensisce(Name alias, Table<RecensisceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Recensisce(Name alias, Table<RecensisceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>RECENSISCE</code> table reference
     */
    public Recensisce(String alias) {
        this(DSL.name(alias), RECENSISCE);
    }

    /**
     * Create an aliased <code>RECENSISCE</code> table reference
     */
    public Recensisce(Name alias) {
        this(alias, RECENSISCE);
    }

    /**
     * Create a <code>RECENSISCE</code> table reference
     */
    public Recensisce() {
        this(DSL.name("RECENSISCE"), null);
    }

    public <O extends Record> Recensisce(Table<O> child, ForeignKey<O, RecensisceRecord> key) {
        super(child, key, RECENSISCE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<RecensisceRecord> getPrimaryKey() {
        return Keys.RECENSISCE__PK_RECENSISCE;
    }

    @Override
    public List<ForeignKey<RecensisceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RECENSISCE__FK_RECENSISCE_PK_GARA, Keys.RECENSISCE__FK_RECENSISCE_PK_CONCORRENTE);
    }

    private transient Gara _gara;
    private transient Concorrente _concorrente;

    /**
     * Get the implicit join path to the <code>GARA</code> table.
     */
    public Gara gara() {
        if (_gara == null)
            _gara = new Gara(this, Keys.RECENSISCE__FK_RECENSISCE_PK_GARA);

        return _gara;
    }

    /**
     * Get the implicit join path to the <code>CONCORRENTE</code> table.
     */
    public Concorrente concorrente() {
        if (_concorrente == null)
            _concorrente = new Concorrente(this, Keys.RECENSISCE__FK_RECENSISCE_PK_CONCORRENTE);

        return _concorrente;
    }

    @Override
    public Recensisce as(String alias) {
        return new Recensisce(DSL.name(alias), this);
    }

    @Override
    public Recensisce as(Name alias) {
        return new Recensisce(alias, this);
    }

    @Override
    public Recensisce as(Table<?> alias) {
        return new Recensisce(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Recensisce rename(String name) {
        return new Recensisce(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Recensisce rename(Name name) {
        return new Recensisce(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Recensisce rename(Table<?> name) {
        return new Recensisce(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
