/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables;


import db_jooq.DefaultSchema;
import db_jooq.Keys;
import db_jooq.tables.records.SedeRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sede extends TableImpl<SedeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SEDE</code>
     */
    public static final Sede SEDE = new Sede();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SedeRecord> getRecordType() {
        return SedeRecord.class;
    }

    /**
     * The column <code>SEDE.ID</code>.
     */
    public final TableField<SedeRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>SEDE.Indirizzo</code>.
     */
    public final TableField<SedeRecord, String> INDIRIZZO = createField(DSL.name("Indirizzo"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>SEDE.Citta</code>.
     */
    public final TableField<SedeRecord, String> CITTA = createField(DSL.name("Citta"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>SEDE.Cap</code>.
     */
    public final TableField<SedeRecord, String> CAP = createField(DSL.name("Cap"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    private Sede(Name alias, Table<SedeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Sede(Name alias, Table<SedeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>SEDE</code> table reference
     */
    public Sede(String alias) {
        this(DSL.name(alias), SEDE);
    }

    /**
     * Create an aliased <code>SEDE</code> table reference
     */
    public Sede(Name alias) {
        this(alias, SEDE);
    }

    /**
     * Create a <code>SEDE</code> table reference
     */
    public Sede() {
        this(DSL.name("SEDE"), null);
    }

    public <O extends Record> Sede(Table<O> child, ForeignKey<O, SedeRecord> key) {
        super(child, key, SEDE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<SedeRecord> getPrimaryKey() {
        return Keys.SEDE__PK_SEDE;
    }

    @Override
    public Sede as(String alias) {
        return new Sede(DSL.name(alias), this);
    }

    @Override
    public Sede as(Name alias) {
        return new Sede(alias, this);
    }

    @Override
    public Sede as(Table<?> alias) {
        return new Sede(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sede rename(String name) {
        return new Sede(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sede rename(Name name) {
        return new Sede(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sede rename(Table<?> name) {
        return new Sede(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
