/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables.records;


import db_jooq.tables.Amministratore;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmministratoreRecord extends UpdatableRecordImpl<AmministratoreRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>AMMINISTRATORE.CF</code>.
     */
    public void setCf(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>AMMINISTRATORE.CF</code>.
     */
    public String getCf() {
        return (String) get(0);
    }

    /**
     * Setter for <code>AMMINISTRATORE.Nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>AMMINISTRATORE.Nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>AMMINISTRATORE.Cognome</code>.
     */
    public void setCognome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>AMMINISTRATORE.Cognome</code>.
     */
    public String getCognome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>AMMINISTRATORE.Email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>AMMINISTRATORE.Email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Amministratore.AMMINISTRATORE.CF;
    }

    @Override
    public Field<String> field2() {
        return Amministratore.AMMINISTRATORE.NOME;
    }

    @Override
    public Field<String> field3() {
        return Amministratore.AMMINISTRATORE.COGNOME;
    }

    @Override
    public Field<String> field4() {
        return Amministratore.AMMINISTRATORE.EMAIL;
    }

    @Override
    public String component1() {
        return getCf();
    }

    @Override
    public String component2() {
        return getNome();
    }

    @Override
    public String component3() {
        return getCognome();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String value1() {
        return getCf();
    }

    @Override
    public String value2() {
        return getNome();
    }

    @Override
    public String value3() {
        return getCognome();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public AmministratoreRecord value1(String value) {
        setCf(value);
        return this;
    }

    @Override
    public AmministratoreRecord value2(String value) {
        setNome(value);
        return this;
    }

    @Override
    public AmministratoreRecord value3(String value) {
        setCognome(value);
        return this;
    }

    @Override
    public AmministratoreRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AmministratoreRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AmministratoreRecord
     */
    public AmministratoreRecord() {
        super(Amministratore.AMMINISTRATORE);
    }

    /**
     * Create a detached, initialised AmministratoreRecord
     */
    public AmministratoreRecord(String cf, String nome, String cognome, String email) {
        super(Amministratore.AMMINISTRATORE);

        setCf(cf);
        setNome(nome);
        setCognome(cognome);
        setEmail(email);
        resetChangedOnNotNull();
    }
}
