/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables.records;


import db_jooq.tables.Campogara;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampogaraRecord extends UpdatableRecordImpl<CampogaraRecord> implements Record4<String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CAMPOGARA.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CAMPOGARA.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CAMPOGARA.Paese</code>.
     */
    public void setPaese(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CAMPOGARA.Paese</code>.
     */
    public String getPaese() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CAMPOGARA.CorpoIdrico</code>.
     */
    public void setCorpoidrico(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CAMPOGARA.CorpoIdrico</code>.
     */
    public String getCorpoidrico() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CAMPOGARA.Lunghezza</code>.
     */
    public void setLunghezza(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>CAMPOGARA.Lunghezza</code>.
     */
    public Integer getLunghezza() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Campogara.CAMPOGARA.ID;
    }

    @Override
    public Field<String> field2() {
        return Campogara.CAMPOGARA.PAESE;
    }

    @Override
    public Field<String> field3() {
        return Campogara.CAMPOGARA.CORPOIDRICO;
    }

    @Override
    public Field<Integer> field4() {
        return Campogara.CAMPOGARA.LUNGHEZZA;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPaese();
    }

    @Override
    public String component3() {
        return getCorpoidrico();
    }

    @Override
    public Integer component4() {
        return getLunghezza();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPaese();
    }

    @Override
    public String value3() {
        return getCorpoidrico();
    }

    @Override
    public Integer value4() {
        return getLunghezza();
    }

    @Override
    public CampogaraRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public CampogaraRecord value2(String value) {
        setPaese(value);
        return this;
    }

    @Override
    public CampogaraRecord value3(String value) {
        setCorpoidrico(value);
        return this;
    }

    @Override
    public CampogaraRecord value4(Integer value) {
        setLunghezza(value);
        return this;
    }

    @Override
    public CampogaraRecord values(String value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampogaraRecord
     */
    public CampogaraRecord() {
        super(Campogara.CAMPOGARA);
    }

    /**
     * Create a detached, initialised CampogaraRecord
     */
    public CampogaraRecord(String id, String paese, String corpoidrico, Integer lunghezza) {
        super(Campogara.CAMPOGARA);

        setId(id);
        setPaese(paese);
        setCorpoidrico(corpoidrico);
        setLunghezza(lunghezza);
        resetChangedOnNotNull();
    }
}
