/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables.records;


import db_jooq.tables.Concorrente;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConcorrenteRecord extends UpdatableRecordImpl<ConcorrenteRecord> implements Record6<String, String, String, String, LocalDate, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CONCORRENTE.CF</code>.
     */
    public void setCf(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CONCORRENTE.CF</code>.
     */
    public String getCf() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CONCORRENTE.Nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CONCORRENTE.Nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CONCORRENTE.Cognome</code>.
     */
    public void setCognome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CONCORRENTE.Cognome</code>.
     */
    public String getCognome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CONCORRENTE.Email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CONCORRENTE.Email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CONCORRENTE.Nascita</code>.
     */
    public void setNascita(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>CONCORRENTE.Nascita</code>.
     */
    public LocalDate getNascita() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>CONCORRENTE.Societa</code>.
     */
    public void setSocieta(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CONCORRENTE.Societa</code>.
     */
    public String getSocieta() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, LocalDate, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, LocalDate, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Concorrente.CONCORRENTE.CF;
    }

    @Override
    public Field<String> field2() {
        return Concorrente.CONCORRENTE.NOME;
    }

    @Override
    public Field<String> field3() {
        return Concorrente.CONCORRENTE.COGNOME;
    }

    @Override
    public Field<String> field4() {
        return Concorrente.CONCORRENTE.EMAIL;
    }

    @Override
    public Field<LocalDate> field5() {
        return Concorrente.CONCORRENTE.NASCITA;
    }

    @Override
    public Field<String> field6() {
        return Concorrente.CONCORRENTE.SOCIETA;
    }

    @Override
    public String component1() {
        return getCf();
    }

    @Override
    public String component2() {
        return getNome();
    }

    @Override
    public String component3() {
        return getCognome();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public LocalDate component5() {
        return getNascita();
    }

    @Override
    public String component6() {
        return getSocieta();
    }

    @Override
    public String value1() {
        return getCf();
    }

    @Override
    public String value2() {
        return getNome();
    }

    @Override
    public String value3() {
        return getCognome();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public LocalDate value5() {
        return getNascita();
    }

    @Override
    public String value6() {
        return getSocieta();
    }

    @Override
    public ConcorrenteRecord value1(String value) {
        setCf(value);
        return this;
    }

    @Override
    public ConcorrenteRecord value2(String value) {
        setNome(value);
        return this;
    }

    @Override
    public ConcorrenteRecord value3(String value) {
        setCognome(value);
        return this;
    }

    @Override
    public ConcorrenteRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public ConcorrenteRecord value5(LocalDate value) {
        setNascita(value);
        return this;
    }

    @Override
    public ConcorrenteRecord value6(String value) {
        setSocieta(value);
        return this;
    }

    @Override
    public ConcorrenteRecord values(String value1, String value2, String value3, String value4, LocalDate value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConcorrenteRecord
     */
    public ConcorrenteRecord() {
        super(Concorrente.CONCORRENTE);
    }

    /**
     * Create a detached, initialised ConcorrenteRecord
     */
    public ConcorrenteRecord(String cf, String nome, String cognome, String email, LocalDate nascita, String societa) {
        super(Concorrente.CONCORRENTE);

        setCf(cf);
        setNome(nome);
        setCognome(cognome);
        setEmail(email);
        setNascita(nascita);
        setSocieta(societa);
        resetChangedOnNotNull();
    }
}
