/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables.records;


import db_jooq.tables.Iscrive;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IscriveRecord extends UpdatableRecordImpl<IscriveRecord> implements Record6<Integer, String, String, LocalDate, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ISCRIVE.IdIscrizione</code>.
     */
    public void setIdiscrizione(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ISCRIVE.IdIscrizione</code>.
     */
    public Integer getIdiscrizione() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ISCRIVE.CodiceGara</code>.
     */
    public void setCodicegara(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ISCRIVE.CodiceGara</code>.
     */
    public String getCodicegara() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ISCRIVE.Concorrente</code>.
     */
    public void setConcorrente(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ISCRIVE.Concorrente</code>.
     */
    public String getConcorrente() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ISCRIVE.DataIscrizione</code>.
     */
    public void setDataiscrizione(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>ISCRIVE.DataIscrizione</code>.
     */
    public LocalDate getDataiscrizione() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>ISCRIVE.NumIscrizione</code>.
     */
    public void setNumiscrizione(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ISCRIVE.NumIscrizione</code>.
     */
    public Integer getNumiscrizione() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ISCRIVE.Societa</code>.
     */
    public void setSocieta(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ISCRIVE.Societa</code>.
     */
    public String getSocieta() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, LocalDate, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, LocalDate, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Iscrive.ISCRIVE.IDISCRIZIONE;
    }

    @Override
    public Field<String> field2() {
        return Iscrive.ISCRIVE.CODICEGARA;
    }

    @Override
    public Field<String> field3() {
        return Iscrive.ISCRIVE.CONCORRENTE;
    }

    @Override
    public Field<LocalDate> field4() {
        return Iscrive.ISCRIVE.DATAISCRIZIONE;
    }

    @Override
    public Field<Integer> field5() {
        return Iscrive.ISCRIVE.NUMISCRIZIONE;
    }

    @Override
    public Field<String> field6() {
        return Iscrive.ISCRIVE.SOCIETA;
    }

    @Override
    public Integer component1() {
        return getIdiscrizione();
    }

    @Override
    public String component2() {
        return getCodicegara();
    }

    @Override
    public String component3() {
        return getConcorrente();
    }

    @Override
    public LocalDate component4() {
        return getDataiscrizione();
    }

    @Override
    public Integer component5() {
        return getNumiscrizione();
    }

    @Override
    public String component6() {
        return getSocieta();
    }

    @Override
    public Integer value1() {
        return getIdiscrizione();
    }

    @Override
    public String value2() {
        return getCodicegara();
    }

    @Override
    public String value3() {
        return getConcorrente();
    }

    @Override
    public LocalDate value4() {
        return getDataiscrizione();
    }

    @Override
    public Integer value5() {
        return getNumiscrizione();
    }

    @Override
    public String value6() {
        return getSocieta();
    }

    @Override
    public IscriveRecord value1(Integer value) {
        setIdiscrizione(value);
        return this;
    }

    @Override
    public IscriveRecord value2(String value) {
        setCodicegara(value);
        return this;
    }

    @Override
    public IscriveRecord value3(String value) {
        setConcorrente(value);
        return this;
    }

    @Override
    public IscriveRecord value4(LocalDate value) {
        setDataiscrizione(value);
        return this;
    }

    @Override
    public IscriveRecord value5(Integer value) {
        setNumiscrizione(value);
        return this;
    }

    @Override
    public IscriveRecord value6(String value) {
        setSocieta(value);
        return this;
    }

    @Override
    public IscriveRecord values(Integer value1, String value2, String value3, LocalDate value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IscriveRecord
     */
    public IscriveRecord() {
        super(Iscrive.ISCRIVE);
    }

    /**
     * Create a detached, initialised IscriveRecord
     */
    public IscriveRecord(Integer idiscrizione, String codicegara, String concorrente, LocalDate dataiscrizione, Integer numiscrizione, String societa) {
        super(Iscrive.ISCRIVE);

        setIdiscrizione(idiscrizione);
        setCodicegara(codicegara);
        setConcorrente(concorrente);
        setDataiscrizione(dataiscrizione);
        setNumiscrizione(numiscrizione);
        setSocieta(societa);
        resetChangedOnNotNull();
    }
}
