/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables.records;


import db_jooq.tables.Recensisce;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecensisceRecord extends UpdatableRecordImpl<RecensisceRecord> implements Record6<String, String, String, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>RECENSISCE.IdRecensione</code>.
     */
    public void setIdrecensione(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>RECENSISCE.IdRecensione</code>.
     */
    public String getIdrecensione() {
        return (String) get(0);
    }

    /**
     * Setter for <code>RECENSISCE.CodiceGara</code>.
     */
    public void setCodicegara(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>RECENSISCE.CodiceGara</code>.
     */
    public String getCodicegara() {
        return (String) get(1);
    }

    /**
     * Setter for <code>RECENSISCE.Concorrente</code>.
     */
    public void setConcorrente(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>RECENSISCE.Concorrente</code>.
     */
    public String getConcorrente() {
        return (String) get(2);
    }

    /**
     * Setter for <code>RECENSISCE.Titolo</code>.
     */
    public void setTitolo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>RECENSISCE.Titolo</code>.
     */
    public String getTitolo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>RECENSISCE.Voto</code>.
     */
    public void setVoto(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>RECENSISCE.Voto</code>.
     */
    public Integer getVoto() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>RECENSISCE.Commento</code>.
     */
    public void setCommento(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>RECENSISCE.Commento</code>.
     */
    public String getCommento() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Recensisce.RECENSISCE.IDRECENSIONE;
    }

    @Override
    public Field<String> field2() {
        return Recensisce.RECENSISCE.CODICEGARA;
    }

    @Override
    public Field<String> field3() {
        return Recensisce.RECENSISCE.CONCORRENTE;
    }

    @Override
    public Field<String> field4() {
        return Recensisce.RECENSISCE.TITOLO;
    }

    @Override
    public Field<Integer> field5() {
        return Recensisce.RECENSISCE.VOTO;
    }

    @Override
    public Field<String> field6() {
        return Recensisce.RECENSISCE.COMMENTO;
    }

    @Override
    public String component1() {
        return getIdrecensione();
    }

    @Override
    public String component2() {
        return getCodicegara();
    }

    @Override
    public String component3() {
        return getConcorrente();
    }

    @Override
    public String component4() {
        return getTitolo();
    }

    @Override
    public Integer component5() {
        return getVoto();
    }

    @Override
    public String component6() {
        return getCommento();
    }

    @Override
    public String value1() {
        return getIdrecensione();
    }

    @Override
    public String value2() {
        return getCodicegara();
    }

    @Override
    public String value3() {
        return getConcorrente();
    }

    @Override
    public String value4() {
        return getTitolo();
    }

    @Override
    public Integer value5() {
        return getVoto();
    }

    @Override
    public String value6() {
        return getCommento();
    }

    @Override
    public RecensisceRecord value1(String value) {
        setIdrecensione(value);
        return this;
    }

    @Override
    public RecensisceRecord value2(String value) {
        setCodicegara(value);
        return this;
    }

    @Override
    public RecensisceRecord value3(String value) {
        setConcorrente(value);
        return this;
    }

    @Override
    public RecensisceRecord value4(String value) {
        setTitolo(value);
        return this;
    }

    @Override
    public RecensisceRecord value5(Integer value) {
        setVoto(value);
        return this;
    }

    @Override
    public RecensisceRecord value6(String value) {
        setCommento(value);
        return this;
    }

    @Override
    public RecensisceRecord values(String value1, String value2, String value3, String value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecensisceRecord
     */
    public RecensisceRecord() {
        super(Recensisce.RECENSISCE);
    }

    /**
     * Create a detached, initialised RecensisceRecord
     */
    public RecensisceRecord(String idrecensione, String codicegara, String concorrente, String titolo, Integer voto, String commento) {
        super(Recensisce.RECENSISCE);

        setIdrecensione(idrecensione);
        setCodicegara(codicegara);
        setConcorrente(concorrente);
        setTitolo(titolo);
        setVoto(voto);
        setCommento(commento);
        resetChangedOnNotNull();
    }
}
