/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables.records;


import db_jooq.tables.Sede;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SedeRecord extends UpdatableRecordImpl<SedeRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SEDE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>SEDE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>SEDE.Indirizzo</code>.
     */
    public void setIndirizzo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SEDE.Indirizzo</code>.
     */
    public String getIndirizzo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SEDE.Citta</code>.
     */
    public void setCitta(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SEDE.Citta</code>.
     */
    public String getCitta() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SEDE.Cap</code>.
     */
    public void setCap(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SEDE.Cap</code>.
     */
    public String getCap() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Sede.SEDE.ID;
    }

    @Override
    public Field<String> field2() {
        return Sede.SEDE.INDIRIZZO;
    }

    @Override
    public Field<String> field3() {
        return Sede.SEDE.CITTA;
    }

    @Override
    public Field<String> field4() {
        return Sede.SEDE.CAP;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getIndirizzo();
    }

    @Override
    public String component3() {
        return getCitta();
    }

    @Override
    public String component4() {
        return getCap();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getIndirizzo();
    }

    @Override
    public String value3() {
        return getCitta();
    }

    @Override
    public String value4() {
        return getCap();
    }

    @Override
    public SedeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SedeRecord value2(String value) {
        setIndirizzo(value);
        return this;
    }

    @Override
    public SedeRecord value3(String value) {
        setCitta(value);
        return this;
    }

    @Override
    public SedeRecord value4(String value) {
        setCap(value);
        return this;
    }

    @Override
    public SedeRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SedeRecord
     */
    public SedeRecord() {
        super(Sede.SEDE);
    }

    /**
     * Create a detached, initialised SedeRecord
     */
    public SedeRecord(Integer id, String indirizzo, String citta, String cap) {
        super(Sede.SEDE);

        setId(id);
        setIndirizzo(indirizzo);
        setCitta(citta);
        setCap(cap);
        resetChangedOnNotNull();
    }
}
