/*
 * This file is generated by jOOQ.
 */
package db_jooq.tables.records;


import db_jooq.tables.Settore;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettoreRecord extends UpdatableRecordImpl<SettoreRecord> implements Record4<String, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SETTORE.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>SETTORE.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>SETTORE.Lunghezza</code>.
     */
    public void setLunghezza(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>SETTORE.Lunghezza</code>.
     */
    public Integer getLunghezza() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>SETTORE.Descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SETTORE.Descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SETTORE.CampoGara</code>.
     */
    public void setCampogara(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SETTORE.CampoGara</code>.
     */
    public String getCampogara() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Settore.SETTORE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Settore.SETTORE.LUNGHEZZA;
    }

    @Override
    public Field<String> field3() {
        return Settore.SETTORE.DESCRIZIONE;
    }

    @Override
    public Field<String> field4() {
        return Settore.SETTORE.CAMPOGARA;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getLunghezza();
    }

    @Override
    public String component3() {
        return getDescrizione();
    }

    @Override
    public String component4() {
        return getCampogara();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getLunghezza();
    }

    @Override
    public String value3() {
        return getDescrizione();
    }

    @Override
    public String value4() {
        return getCampogara();
    }

    @Override
    public SettoreRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SettoreRecord value2(Integer value) {
        setLunghezza(value);
        return this;
    }

    @Override
    public SettoreRecord value3(String value) {
        setDescrizione(value);
        return this;
    }

    @Override
    public SettoreRecord value4(String value) {
        setCampogara(value);
        return this;
    }

    @Override
    public SettoreRecord values(String value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SettoreRecord
     */
    public SettoreRecord() {
        super(Settore.SETTORE);
    }

    /**
     * Create a detached, initialised SettoreRecord
     */
    public SettoreRecord(String id, Integer lunghezza, String descrizione, String campogara) {
        super(Settore.SETTORE);

        setId(id);
        setLunghezza(lunghezza);
        setDescrizione(descrizione);
        setCampogara(campogara);
        resetChangedOnNotNull();
    }
}
