// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Amministratore {
	/**
	 * 
	 */
	public String CFAmministratore;
	/**
	 * 
	 */
	private String Nome;
	/**
				 * 
				 */
				private String Cognome;

	/**
	 * 
	 */
	public void annunciaGara(): void() {
	}

	/**
	 * 
	 */
	public void valutaProposte(): boolean() {
	}

	/**
	 * 
	 */
	public void preparaGara(): void() {
	}

	/**
	 * 
	 */
	public void sospendeArbitro(in CFArbitro: String): void() {
	}

	/**
	 * 
	 */
	public void creaGara(in NP: Integer, in org: String, in t_tec: Tenica, in crPunti: String, in Data: Date, in n_max: Integer, in n_min: Integer, in stato: StatoGara, in tipo: TipologiaGara, in anno: Date): void () {
	}
}
