// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Arbitro {
	/**
	 * 
	 */
	public String CFArbitro;
	/**
	 * 
	 */
	private String Nome;
	/**
	 * 
	 */
	private String Cognome;
	/**
				 * 
				 */
				private String Sezione;

	/**
	 * 
	 */
	public void assegnaGruppi(in concorrenti: List<Concorrente>): void() {
	}

	/**
	 * 
	 */
	public void registraRisultati(in CodiceGara: String): boolean() {
	}

	/**
	 * 
	 */
	public void segnaPunteggio(in CodiceGara: String, in CF: String): boolean() {
	}

	/**
	 * 
	 */
	public void rinviaGara(in CodiceGara): void() {
	}

	/**
	 * 
	 */
	public void penalizza(in CF: String, in penalita: Float): void() {
	}

	/**
	 * 
	 */
	public void squalificaConcorrente(in CF: String): void() {
	}

	/**
	 * 
	 */
	public void pubblicaRisultati(in CodiceGara: String): void() {
	}
}
