// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Campo gara
{
	/**
	 * 
	 */
	public String IdCampoGara;
	/**
	 * 
	 */
	private String CorpoIdrico;
	/**
	 * 
	 */
	private String Paese;
	/**
	 * 
	 */
	private int Lunghezza;
}
