// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Campionato {
	/**
	 * 
	 */
	public String Titolo;
	/**
	 * 
	 */
	private String Categoria;
}
