// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Concorrente {
	/**
	 * 
	 */
	public String CF;
	/**
	 * 
	 */
	private String Cognome;
	/**
	 * 
	 */
	private String Nome;
	/**
	 * 
	 */
	private EDate Nascita;

	/**
	 * 
	 */
	public void cercaConcorrente(in CF: String):

	Concorrente() {
	}

	/**
	 * 
	 */
	public void cambiaSponsor(in CF: String, in Sp: Sponsor): void() {
	}

	/**
	 * 
	 */
	public void cambiaSocieta(in CF: String, in Soc: Societa): void() {
	}

	/**
	 * 
	 */
	public void recensisce(in CodiceGara: String): void() {
	}

	/**
	 * 
	 */
	public void valutaArbitro(in CFArbitro: String): void() {
	}
}
