// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Gara {
	/**
	 * 
	 */
	public String CodiceGara;
	/**
	 * 
	 */
	private int NProva;
	/**
	 * 
	 */
	private String Organizzatore;
	/**
	 * 
	 */
	private Tecnica TipoTecnica;
	/**
	 * 
	 */
	private String CriterioPunti;
	/**
	 * 
	 */
	private EDate DataSvolgimento;
	/**
	 * 
	 */
	private int MaxPersone;
	/**
	 * 
	 */
	private int MinPersone;
	/**
	 * 
	 */
	private StatoGara Stato;
	/**
	 * 
	 */
	private TipologiaGara TipoGara;
	/**
	 * 
	 */
	private EDate AnnoGara;

	/**
	 * 
	 */
	public void notifica(): void() {
	}

	/**
	 * 
	 */
	public void iscrivi(in CF: String): boolean() {
	}

	/**
	 * 
	 */
	public void annullaGara(in CodiceGara: String, out Stato: StatoGara): void() {
	}

	/**
	 * 
	 */
	public void inviaClassifica(): void() {
	}

	/**
	 * 
	 */
	public void cercaGara(in CodiceGara: String): List<Gara>() {
	}

	/**
	 * 
	 */
	public void cercaGara(in IdCampoGara: String): List<Gara>() {
	}

	/**
	 * 
	 */
	public void cercaGara(in DataGara: Date): List<Gara>() {
	}

	/**
	 * 
	 */
	public void cercaGara(in CF: String): List<Gara>() {
	}

	/**
	 * 
	 */
	public void cercaMeteo(in CampoGara):

	String() {
	}
}
