// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Sede {
	/**
	 * 
	 */
	public int IDSede;
	/**
	 * 
	 */
	private String Indirizzo;
	/**
	 * 
	 */
	private String Citta;
	/**
	 * 
	 */
	private String CAP;
}
