// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Settore {
	/**
	 * 
	 */
	public String IDSettore;
	/**
	 * 
	 */
	private String Descrizione;
}
