// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Società {
	/**
	 * 
	 */
	private String nome;

	/**
	 * 
	 * @param concorrenti 
	 * @return 
	 * @param codiceGara 
	 */
	public boolean iscrizioneGaraGruppi(Concorrente[] concorrenti, String codiceGara) {
	}

	/**
	 * 
	 * @return 
	 * @param concorrente 
	 * @param codiceGara 
	 */
	public boolean iscrizioneGaraSingolo(Concorrente concorrente, String codiceGara) {
	}

	/**
	 * 
	 */
	public void getProfilo() {
	}

	/**
	 * 
	 * @param concorrente 
	 */
	public void aggiungiSocio(Concorrente concorrente) {
	}

	/**
	 * 
	 * @param concorrente 
	 */
	public void abbandonoSocio(Concorrente concorrente) {
	}

	/**
	 * 
	 */
	public void modificaProfilo() {
	}

	/**
	 * 
	 * @param gara 
	 */
	public void nuovaGara(Gara gara) {
	}

	/**
	 * 
	 * @return 
	 */
	public String regolamento() {
	}
}
