// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Società {
	/**
	 * 
	 */
	public String IDSocieta;
	/**
				 * 
				 */
				private String Nome;

	/**
	 * 
	 */
	public void proponiGara(in Descrizione: String): void() {
	}
}
