// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Sponsor {
	/**
	 * 
	 */
	public String IDSponsor;
	/**
	 * 
	 */
	private String Nome;
	/**
	 * 
	 */
	private String paginaWeb;
}
