// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Turno {
	/**
	 * 
	 */
	public String CodiceTurno;
	/**
	 * 
	 */
	private String Durata;
}
