/*
 * This file is generated by jOOQ.
 */
package db_jooq;


import db_jooq.tables.Amministratore;
import db_jooq.tables.Arbitro;
import db_jooq.tables.Campionato;
import db_jooq.tables.Campogara;
import db_jooq.tables.Concorrente;
import db_jooq.tables.Contratto;
import db_jooq.tables.Gara;
import db_jooq.tables.Iscrive;
import db_jooq.tables.Partecipa;
import db_jooq.tables.Recensisce;
import db_jooq.tables.Sede;
import db_jooq.tables.Settore;
import db_jooq.tables.Societa;
import db_jooq.tables.Sponsor;
import db_jooq.tables.Turno;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>AMMINISTRATORE</code>.
     */
    public final Amministratore AMMINISTRATORE = Amministratore.AMMINISTRATORE;

    /**
     * The table <code>ARBITRO</code>.
     */
    public final Arbitro ARBITRO = Arbitro.ARBITRO;

    /**
     * The table <code>CAMPIONATO</code>.
     */
    public final Campionato CAMPIONATO = Campionato.CAMPIONATO;

    /**
     * The table <code>CAMPOGARA</code>.
     */
    public final Campogara CAMPOGARA = Campogara.CAMPOGARA;

    /**
     * The table <code>CONCORRENTE</code>.
     */
    public final Concorrente CONCORRENTE = Concorrente.CONCORRENTE;

    /**
     * The table <code>CONTRATTO</code>.
     */
    public final Contratto CONTRATTO = Contratto.CONTRATTO;

    /**
     * The table <code>GARA</code>.
     */
    public final Gara GARA = Gara.GARA;

    /**
     * The table <code>ISCRIVE</code>.
     */
    public final Iscrive ISCRIVE = Iscrive.ISCRIVE;

    /**
     * The table <code>PARTECIPA</code>.
     */
    public final Partecipa PARTECIPA = Partecipa.PARTECIPA;

    /**
     * The table <code>RECENSISCE</code>.
     */
    public final Recensisce RECENSISCE = Recensisce.RECENSISCE;

    /**
     * The table <code>SEDE</code>.
     */
    public final Sede SEDE = Sede.SEDE;

    /**
     * The table <code>SETTORE</code>.
     */
    public final Settore SETTORE = Settore.SETTORE;

    /**
     * The table <code>SOCIETA</code>.
     */
    public final Societa SOCIETA = Societa.SOCIETA;

    /**
     * The table <code>SPONSOR</code>.
     */
    public final Sponsor SPONSOR = Sponsor.SPONSOR;

    /**
     * The table <code>TURNO</code>.
     */
    public final Turno TURNO = Turno.TURNO;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Amministratore.AMMINISTRATORE,
            Arbitro.ARBITRO,
            Campionato.CAMPIONATO,
            Campogara.CAMPOGARA,
            Concorrente.CONCORRENTE,
            Contratto.CONTRATTO,
            Gara.GARA,
            Iscrive.ISCRIVE,
            Partecipa.PARTECIPA,
            Recensisce.RECENSISCE,
            Sede.SEDE,
            Settore.SETTORE,
            Societa.SOCIETA,
            Sponsor.SPONSOR,
            Turno.TURNO
        );
    }
}
