/*
 * This file is generated by jOOQ.
 */
package db_jooq;


import db_jooq.tables.Amministratore;
import db_jooq.tables.Arbitro;
import db_jooq.tables.Campionato;
import db_jooq.tables.Campogara;
import db_jooq.tables.Concorrente;
import db_jooq.tables.Contratto;
import db_jooq.tables.Gara;
import db_jooq.tables.Iscrive;
import db_jooq.tables.Partecipa;
import db_jooq.tables.Recensisce;
import db_jooq.tables.Sede;
import db_jooq.tables.Settore;
import db_jooq.tables.Societa;
import db_jooq.tables.Sponsor;
import db_jooq.tables.Turno;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>AMMINISTRATORE</code>.
     */
    public static final Amministratore AMMINISTRATORE = Amministratore.AMMINISTRATORE;

    /**
     * The table <code>ARBITRO</code>.
     */
    public static final Arbitro ARBITRO = Arbitro.ARBITRO;

    /**
     * The table <code>CAMPIONATO</code>.
     */
    public static final Campionato CAMPIONATO = Campionato.CAMPIONATO;

    /**
     * The table <code>CAMPOGARA</code>.
     */
    public static final Campogara CAMPOGARA = Campogara.CAMPOGARA;

    /**
     * The table <code>CONCORRENTE</code>.
     */
    public static final Concorrente CONCORRENTE = Concorrente.CONCORRENTE;

    /**
     * The table <code>CONTRATTO</code>.
     */
    public static final Contratto CONTRATTO = Contratto.CONTRATTO;

    /**
     * The table <code>GARA</code>.
     */
    public static final Gara GARA = Gara.GARA;

    /**
     * The table <code>ISCRIVE</code>.
     */
    public static final Iscrive ISCRIVE = Iscrive.ISCRIVE;

    /**
     * The table <code>PARTECIPA</code>.
     */
    public static final Partecipa PARTECIPA = Partecipa.PARTECIPA;

    /**
     * The table <code>RECENSISCE</code>.
     */
    public static final Recensisce RECENSISCE = Recensisce.RECENSISCE;

    /**
     * The table <code>SEDE</code>.
     */
    public static final Sede SEDE = Sede.SEDE;

    /**
     * The table <code>SETTORE</code>.
     */
    public static final Settore SETTORE = Settore.SETTORE;

    /**
     * The table <code>SOCIETA</code>.
     */
    public static final Societa SOCIETA = Societa.SOCIETA;

    /**
     * The table <code>SPONSOR</code>.
     */
    public static final Sponsor SPONSOR = Sponsor.SPONSOR;

    /**
     * The table <code>TURNO</code>.
     */
    public static final Turno TURNO = Turno.TURNO;
}
