// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class Amministratore {
	/**
	 * 
	 */
	public String cfAmministratore;
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private String cognome;

	/**
	 * 
	 * @param gara 
	 */
	public void nuovaGara(Gara gara) {
	}

	/**
	 * 
	 * @param numGara 
	 */
	public void confermaProposta(int numGara) {
	}

	/**
	 * 
	 * @param numGara 
	 * @param motivo 
	 */
	public void negaProposta(int numGara, String motivo) {
	}

	/**
	 * 
	 */
	private void notificaSocieta() {
	}

	/**
	 * 
	 */
	private void notificaComune() {
	}

	/**
	 * 
	 * @return 
	 */
	public String regolamento() {
	}
}
