// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class Arbitro {
	/**
	 * 
	 */
	public String cfArbitro;
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private String cognome;
	/**
	 * 
	 */
	private String sezione;

	/**
	 * 
	 * @param codice 
	 */
	public void avviaGara(String codice) {
	}

	/**
	 * 
	 * @param codice 
	 */
	public void rinuncia(String codice) {
	}

	/**
	 * 
	 * @param concorrenti 
	 */
	public void segnaAssenze(Concorrente[] concorrenti) {
	}

	/**
	 * 
	 * @param concorrenti 
	 */
	public void generaGruppi(Concorrente[] concorrenti) {
	}

	/**
	 * 
	 * @param concorrente 
	 */
	public void segnaPunto(Concorrente concorrente) {
	}

	/**
	 * 
	 * @param concorrente 
	 * @param punti 
	 */
	public void segnaPunto(Concorrente concorrente, int punti) {
	}

	/**
	 * 
	 * @param concorrente 
	 * @param motivo 
	 */
	public void annullaConcorrente(Concorrente concorrente, String motivo) {
	}

	/**
	 * 
	 * @param concorrente 
	 * @param quantita 
	 * @param motivo 
	 */
	public void penalizzaConcorrente(Concorrente concorrente, int quantita, String motivo) {
	}

	/**
	 * 
	 * @param idSettore 
	 * @param numTurno 
	 */
	public void salvaPunti(String idSettore, int numTurno) {
	}
}
