// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class Campionato {
	/**
	 * 
	 */
	public String titolo;
	/**
	 * 
	 */
	private String categoria;

	/**
	 * 
	 * @return 
	 */
	public Punteggio[] getClassificaTotale() {
	}

	/**
	 * 
	 * @return 
	 * @param numProva 
	 */
	public Punteggio[] classificaProva(int numProva) {
	}
}
