// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Class_Diagram;

/************************************************************/
/**
 * 
 */
public class Campo gara
{
	/**
	 * 
	 */
	public String idCampoGara;
	/**
	 * 
	 */
	private String corpoIdrico;
	/**
	 * 
	 */
	private String paese;
	/**
	 * 
	 */
	private int lunghezza;

	/**
	 * 
	 * @return 
	 */
	public String getCaratteristiche() {
	}

	/**
	 * 
	 */
	public void setCaratteristiche() {
	}
}
