// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class Concorrente {
	/**
	 * 
	 */
	public String cf;
	/**
	 * 
	 */
	private String cognome;
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private EDate nascita;

	/**
	 * 
	 * @return 
	 * @param codice 
	 */
	public boolean iscriviGara(String codice) {
	}

	/**
	 * 
	 * @return 
	 * @param codice 
	 */
	public boolean annullaIscrizione(String codice) {
	}

	/**
	 * 
	 */
	public void visualizzaProfilo() {
	}

	/**
	 * 
	 */
	public void carriera() {
	}

	/**
	 * 
	 */
	public void modificaProfilo() {
	}

	/**
	 * 
	 */
	public void iscrizioni() {
	}

	/**
	 * 
	 * @return 
	 * @param codice 
	 * @param rec 
	 */
	public boolean aggiungiRecensione(String codice, Recensione rec) {
	}
}
