// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class Gara {
	/**
	 * 
	 */
	public String codiceGara;
	/**
	 * 
	 */
	private int nProva;
	/**
	 * 
	 */
	private String organizzatore;
	/**
	 * 
	 */
	private Tecnica tipoTecnica;
	/**
	 * 
	 */
	private String criterioPunti;
	/**
	 * 
	 */
	private EDate dataSvolgimento;
	/**
	 * 
	 */
	private int maxPersone;
	/**
	 * 
	 */
	private int minPersone;
	/**
	 * 
	 */
	private StatoOrganizzazione stato;
	/**
	 * 
	 */
	private TipologiaGara tipoGara;
	/**
	 * 
	 */
	private EDate annoGara;

	/**
	 * 
	 * @param stato 
	 */
	public void cambiaStatoOrganizzazione(StatoOrganizzazione stato) {
	}

	/**
	 * 
	 * @param stato 
	 */
	public void cambiaStatoGara(StatoGara stato) {
	}

	/**
	 * 
	 * @param concorrente 
	 * @param motivo 
	 */
	public void squalifica(Concorrente concorrente, String motivo) {
	}

	/**
	 * 
	 * @param concorrenti 
	 */
	public void preparaTurni(Concorrente[] concorrenti) {
	}

	/**
	 * 
	 * @param turno 
	 * @param gruppo 
	 */
	private void assegnaTurno(Turno turno, Concorrente[] gruppo) {
	}

	/**
	 * 
	 * @param turno 
	 * @param punteggi 
	 */
	public void classificaTurno(Turno turno, Punteggio[] punteggi) {
	}

	/**
	 * 
	 */
	public void trovaArbitro() {
	}

	/**
	 * 
	 * @param cf 
	 * @param numIscritti 
	 * @return 
	 */
	public boolean nuovaIscrizione(String cf, int numIscritti) {
	}

	/**
	 * 
	 * @return 
	 * @param concorrentiPresenti 
	 */
	public boolean iscrizioneMultipla(Concorrente[] concorrentiPresenti) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean verificaData() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean verificaMax() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean verificaMin() {
	}

	/**
	 * 
	 * @return 
	 */
	public Punteggio[] getClassifica() {
	}
}
