// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class Sede {
	/**
	 * 
	 */
	public int idSede;
	/**
	 * 
	 */
	private String indirizzo;
	/**
	 * 
	 */
	private String citta;
	/**
	 * 
	 */
	private String cap;
}
