// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class Settore {
	/**
	 * 
	 */
	public String idSettore;
	/**
	 * 
	 */
	private String descrizione;

	/**
	 * 
	 * @return 
	 */
	public String getCaratteristiche() {
	}

	/**
	 * 
	 */
	public void setCaratteristiche() {
	}
}
