// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class sponsor {
	/**
	 * 
	 */
	public String IdSponsor;
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private String paginaWeb;
}
