// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public enum StatoOrganizzazione {
	/**
	 * 
	 */
	CONFERMATA,
	/**
	 * 
	 */
	IN_ATTESA,
	/**
	 * 
	 */
	ANNULLATA;
}
