// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package applicazione;

/************************************************************/
/**
 * 
 */
public class Turno {
	/**
	 * 
	 */
	public String codiceTurno;
	/**
	 * 
	 */
	private String durata;

	/**
	 * 
	 * @param punteggi 
	 */
	public void calcolaClassifica(Punteggio[] punteggi) {
	}

	/**
	 * 
	 * @return 
	 */
	public Punteggio[] getClassifica() {
	}
}
